#!/usr/bin/env bash
# This script displays "Best School" 10 times using the while loop
#   But for the 9th iteration, that displays "Hi"

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
