#!/usr/bin/env bash 
# This script displays "Best School" 10 times using the while loop
#   Except for the 4th iteration that displays "bad luck"
#     Then the 8th iteration displays "good luck"

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck" 
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
