#!/usr/bin/env bash
#Install haproxy and configurate both servers

apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tbalance roundrobin\n\tserver 73901-web-01 100.25.167.170:80 check\n\tserver 73901-web-02 34.207.190.168:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
