#!/usr/bin/env bash
#Install haproxy and configurate both web-01 and web-02 servers

apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tbalance roundrobin\n\tserver 73901-web-01 54.90.32.107:80 check\n\tserver 73901-web-02 100.26.177.49:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart

