#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

file="holbertonschool"

if [ ! -e $file ];
then
	echo "$file file does not exist"
else
	echo "$file file exists"

	if [ ! -s $file ];
	then
		echo "$file file is empty"
	else
		echo "$file file is not empty"
	fi

	if [ -f $file ];
	then
		echo "holbertonschool is a regular file"
	fi
fi